# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.delete_all
Post.delete_all
Friendship.delete_all
Comment.delete_all
Toast.delete_all


u1 = User.create!(email: "bryanmillstein@gmail.com", user_name: "Bryan Millstein", password: "password")
u2 = User.create!(email: "james@gmail.com", user_name: "James Bond", password: "password")
u4 = User.create!(email: "bobby@gmail.com", user_name: "bobby", password: "password")
u5 = User.create!(email: "bobby@gmail.com", user_name: "bobby", password: "password")
u6 = User.create!(email: "bobby@gmail.com", user_name: "bobby", password: "password")
u7 = User.create!(email: "bobby@gmail.com", user_name: "bobby", password: "password")
u8 = User.create!(email: "bobby@gmail.com", user_name: "bobby", password: "password")
u9 = User.create!(email: "bobby@gmail.com", user_name: "bobby", password: "password")
u10 = User.create!(email: "bobby@gmail.com", user_name: "bobby", password: "password")
u11 = User.create!(email: "bobby@gmail.com", user_name: "bobby", password: "password")
u12 = User.create!(email: "bobby@gmail.com", user_name: "bobby", password: "password")
u13 = User.create!(email: "bobby@gmail.com", user_name: "bobby", password: "password")
u14 = User.create!(email: "bobby@gmail.com", user_name: "bobby", password: "password")
u15 = User.create!(email: "bobby@gmail.com", user_name: "bobby", password: "password")
u16 = User.create!(email: "bobby@gmail.com", user_name: "bobby", password: "password")
u17 = User.create!(email: "bobby@gmail.com", user_name: "bobby", password: "password")
u18 = User.create!(email: "bobby@gmail.com", user_name: "bobby", password: "password")
u19 = User.create!(email: "bobby@gmail.com", user_name: "bobby", password: "password")
u20 = User.create!(email: "bobby@gmail.com", user_name: "bobby", password: "password")

p1 = u1.posts.create!(drink: "Whiskey", body: "Great after a long day.")
p2 = u1.posts.create!(drink: "Scotch", body: "Best drink ever.")
p3 = u2.posts.create!(drink: "Bourbon", body: "Delicious.")
p4 = u2.posts.create!(drink: "Macallan", body: "Best")
p5 = u3.posts.create!(drink: "Laphroaig", body: "Delicious.")
p6 = u4.posts.create!(drink: "Irish Whiskey", body: "Need more...")
p7 = u1.posts.create!(drink: "Whiskey", body: "Great after a long day.")
p8 = u1.posts.create!(drink: "Scotch", body: "Best drink ever.")
p9 = u2.posts.create!(drink: "Bourbon", body: "Delicious.")
p10 = u2.posts.create!(drink: "Macallan", body: "Best")
p11 = u3.posts.create!(drink: "Laphroaig", body: "Delicious.")
p12 = u4.posts.create!(drink: "Irish Whiskey", body: "Need more...")
p13 = u1.posts.create!(drink: "Whiskey", body: "Great after a long day.")
p14 = u1.posts.create!(drink: "Scotch", body: "Best drink ever.")
p15 = u2.posts.create!(drink: "Bourbon", body: "Delicious.")
p16 = u2.posts.create!(drink: "Macallan", body: "Best")
p17 = u3.posts.create!(drink: "Laphroaig", body: "Delicious.")
p18 = u4.posts.create!(drink: "Irish Whiskey", body: "Need more...")
p19 = u1.posts.create!(drink: "Whiskey", body: "Great after a long day.")
p20 = u1.posts.create!(drink: "Scotch", body: "Best drink ever.")
p21 = u2.posts.create!(drink: "Bourbon", body: "Delicious.")
p22 = u2.posts.create!(drink: "Macallan", body: "Best")
p23 = u3.posts.create!(drink: "Laphroaig", body: "Delicious.")
p24 = u4.posts.create!(drink: "Irish Whiskey", body: "Need more...")
p25 = u1.posts.create!(drink: "Whiskey", body: "Great after a long day.")
p26 = u1.posts.create!(drink: "Scotch", body: "Best drink ever.")
p27 = u2.posts.create!(drink: "Bourbon", body: "Delicious.")
p28 = u2.posts.create!(drink: "Macallan", body: "Best")
p29 = u3.posts.create!(drink: "Laphroaig", body: "Delicious.")
p30 = u4.posts.create!(drink: "Irish Whiskey", body: "Need more...")

c1 = u2.comments.create!(post_id: p1.id, body: "Amazing post.")
c1 = u3.comments.create!(post_id: p1.id, body: "Radical post.")
c1 = u1.comments.create!(post_id: p3.id, body: "Cool post.")
c2 = u2.comments.create!(post_id: p5.id, body: "Cooler post.")
c3 = u3.comments.create!(post_id: p4.id, body: "Coolest post.")
c4 = u4.comments.create!(post_id: p5.id, body: "Fine.")
c5 = u3.comments.create!(post_id: p6.id, body: "Coolest post.")


f1 = u1.friendships.create!(friend_id: u2.id)
f2 = u1.friendships.create!(friend_id: u3.id)
f4 = u2.friendships.create!(friend_id: u1.id)
f5 = u3.friendships.create!(friend_id: u1.id)
f6 = u4.friendships.create!(friend_id: u1.id)
f7 = u2.friendships.create!(friend_id: u4.id)
f8 = u4.friendships.create!(friend_id: u2.id)

t1 = p3.toasts.create!(user_id: u1.id)
t2 = p3.toasts.create!(user_id: u2.id)
t3 = p3.toasts.create!(user_id: u3.id)
t4 = p3.toasts.create!(user_id: u4.id)
t5 = p3.toasts.create!(user_id: u5.id)
t6 = p3.toasts.create!(user_id: u6.id)
t7 = p3.toasts.create!(user_id: u7.id)
t8 = p3.toasts.create!(user_id: u8.id)
t9 = p3.toasts.create!(user_id: u9.id)
t10 = p3.toasts.create!(user_id: u10.id)
t11 = p3.toasts.create!(user_id: u11.id)
t12 = p3.toasts.create!(user_id: u12.id)
t13 = p3.toasts.create!(user_id: u13.id)
t14 = p3.toasts.create!(user_id: u14.id)
t15 = p3.toasts.create!(user_id: u15.id)
t16 = p3.toasts.create!(user_id: u16.id)
t17 = p3.toasts.create!(user_id: u17.id)
t18 = p3.toasts.create!(user_id: u18.id)
t19 = p3.toasts.create!(user_id: u19.id)
t20 = p3.toasts.create!(user_id: u20.id)

d1 = Drink.create!(name: "1608", type: "Irish Whiskey", brand: "Bushmills")
d2 = Drink.create!(name: "Rarest Vintage Reserve", type: "Irish Whiskey", brand: "Jameson")
d3 = Drink.create!(name: "Select Reserve Black Barrel", type: "Irish Whiskey", brand: "Jameson")
d4 = Drink.create!(name: "Greenore", type: "Irish Whiskey", brand: "Cooley")
d5 = Drink.create!(name: "1949", type: "Irish Whiskey", brand: "Knappogue Castle")

d6 = Drink.create!(name: "The Quarter Century", type: "Scotch", brand: "Glenmorangie")
d7 = Drink.create!(name: "Extremely Rare", type: "Scotch", brand: "Glenmorangie")
d8 = Drink.create!(name: "25-Year", type: "Scotch", brand: "Macallan")
d9 = Drink.create!(name: "30-Year", type: "Scotch", brand: "Macallan")
d10 = Drink.create!(name: "30-Year", type: "Scotch", brand: "Highland Park")
d11 = Drink.create!(name: "40-Year", type: "Scotch", brand: "Highland Park")
d12 = Drink.create!(name: "Laphroaig Quarter Cask", type: "Scotch", brand: "Laphroaig")
d13 = Drink.create!(name: "40-Year", type: "Scotch", brand: "Laphroaig")
d14 = Drink.create!(name: "Triple Cask 25 Year Old", type: "Scotch", brand: "Balvenie")
d15 = Drink.create!(name: "The Balvenie Fifty", type: "Scotch", brand: "")
d16 = Drink.create!(name: "1937 Rare Collection", type: "Scotch", brand: "Glenfiddich")
d17 = Drink.create!(name: "Millenium Reserve", type: "Scotch", brand: "Glenfiddich")
d18 = Drink.create!(name: "Glenlivet 70yo", type: "Scotch", brand: "Glenlivet")
d19 = Drink.create!(name: "XXV 25 Year Old", type: "Scotch", brand: "Glenlivet")
d20 = Drink.create!(name: "Blue Label", type: "Scotch", brand: "Johnnie Walker")
d20 = Drink.create!(name: "Platinum Label", type: "Scotch", brand: "Johnnie Walker")




d16 = Drink.create!(name: "Jim Beam White", type: "Bourbon", brand: "Jim Beam")
d17 = Drink.create!(name: "Jim Beam Black", type: "Bourbon", brand: "Jim Beam")
d18 = Drink.create!(name: "Gentleman Jack", type: "Bourbon", brand: "Jack Daniel's")
d19 = Drink.create!(name: "Old No. 7", type: "Bourbon", brand: "Jack Daniel's")
d20 = Drink.create!(name: "Knob Creek", type: "Bourbon", brand: "Knob Creek")
d21 = Drink.create!(name: "Knob Creek Single Barrel Reserve", type: "Bourbon", brand: "Knob Creek")
d22 = Drink.create!(name: "Maker’s 46", type: "Bourbon", brand: "Maker's Mark")
d23 = Drink.create!(name: "Maker's Mark Cask Strength Bourbon", type: "Bourbon", brand: "Maker's Mark")
d24 = Drink.create!(name: "Seasoned Oak Finish", type: "Bourbon", brand: "Woodford Reserve")
d25 = Drink.create!(name: "Sweet Mash 1838", type: "Bourbon", brand: "Woodford Reserve")
d26 = Drink.create!(name: "Rare Breed", type: "Bourbon", brand: "Wild Turkey")
d27 = Drink.create!(name: "Bulleit Bourbon 10 Year", type: "Bourbon", brand: "Bulleit Bourbon")
d28 = Drink.create!(name: "Bulleit rye whiskey", type: "Bourbon", brand: "Bulleit Bourbon")
d29 = Drink.create!(name: "Four Roses Mariage Collection", type: "Bourbon", brand: "Four Roses")
d30 = Drink.create!(name: "Hudson Baby Bourbon", type: "Bourbon", brand: "Hudson Baby Bourbon")
